package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCmsNavi<M extends BaseCmsNavi<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNaviParentId(java.lang.Integer naviParentId) {
		set("navi_parent_id", naviParentId);
	}

	public java.lang.Integer getNaviParentId() {
		return get("navi_parent_id");
	}

	public void setNaviName(java.lang.String naviName) {
		set("navi_name", naviName);
	}

	public java.lang.String getNaviName() {
		return get("navi_name");
	}

	public void setNaviUrl(java.lang.String naviUrl) {
		set("navi_url", naviUrl);
	}

	public java.lang.String getNaviUrl() {
		return get("navi_url");
	}

	public void setNaviIcon(java.lang.String naviIcon) {
		set("navi_icon", naviIcon);
	}

	public java.lang.String getNaviIcon() {
		return get("navi_icon");
	}

	public void setNaviLevel(java.lang.Integer naviLevel) {
		set("navi_level", naviLevel);
	}

	public java.lang.Integer getNaviLevel() {
		return get("navi_level");
	}

	public void setNaviOrder(java.lang.Integer naviOrder) {
		set("navi_order", naviOrder);
	}

	public java.lang.Integer getNaviOrder() {
		return get("navi_order");
	}

	public void setNaviNameEn(java.lang.String naviNameEn) {
		set("navi_name_en", naviNameEn);
	}

	public java.lang.String getNaviNameEn() {
		return get("navi_name_en");
	}

	public void setNaviType(java.lang.Integer naviType) {
		set("navi_type", naviType);
	}

	public java.lang.Integer getNaviType() {
		return get("navi_type");
	}

	public void setNaviIsShow(java.lang.Boolean naviIsShow) {
		set("navi_is_show", naviIsShow);
	}

	public java.lang.Boolean getNaviIsShow() {
		return get("navi_is_show");
	}

	public void setNaviIsOut(java.lang.Boolean naviIsOut) {
		set("navi_is_out", naviIsOut);
	}

	public java.lang.Boolean getNaviIsOut() {
		return get("navi_is_out");
	}

}
