package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCmsNaviType<M extends BaseCmsNaviType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNatyName(java.lang.String natyName) {
		set("naty_name", natyName);
	}

	public java.lang.String getNatyName() {
		return get("naty_name");
	}

}
