package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKnGraph<M extends BaseKnGraph<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setKngrNodeSrc(java.lang.String kngrNodeSrc) {
		set("kngr_node_src", kngrNodeSrc);
	}

	public java.lang.String getKngrNodeSrc() {
		return get("kngr_node_src");
	}

	public void setKngrNodeDes(java.lang.String kngrNodeDes) {
		set("kngr_node_des", kngrNodeDes);
	}

	public java.lang.String getKngrNodeDes() {
		return get("kngr_node_des");
	}

}
