package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmAlgorithm<M extends BaseDmAlgorithm<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDmalName(java.lang.String dmalName) {
		set("dmal_name", dmalName);
	}

	public java.lang.String getDmalName() {
		return get("dmal_name");
	}

	public void setDmalDmacId(java.lang.Integer dmalDmacId) {
		set("dmal_dmac_id", dmalDmacId);
	}

	public java.lang.Integer getDmalDmacId() {
		return get("dmal_dmac_id");
	}

	public void setDmalDesc(java.lang.String dmalDesc) {
		set("dmal_desc", dmalDesc);
	}

	public java.lang.String getDmalDesc() {
		return get("dmal_desc");
	}

	public void setDmalCmdPath(java.lang.String dmalCmdPath) {
		set("dmal_cmd_path", dmalCmdPath);
	}

	public java.lang.String getDmalCmdPath() {
		return get("dmal_cmd_path");
	}

	public void setDmalCmdArg(java.lang.String dmalCmdArg) {
		set("dmal_cmd_arg", dmalCmdArg);
	}

	public java.lang.String getDmalCmdArg() {
		return get("dmal_cmd_arg");
	}

	public void setDmalTime(java.util.Date dmalTime) {
		set("dmal_time", dmalTime);
	}

	public java.util.Date getDmalTime() {
		return get("dmal_time");
	}

	public void setDmalUserId(java.lang.Integer dmalUserId) {
		set("dmal_user_id", dmalUserId);
	}

	public java.lang.Integer getDmalUserId() {
		return get("dmal_user_id");
	}

	public void setDmalStatus(java.lang.Boolean dmalStatus) {
		set("dmal_status", dmalStatus);
	}

	public java.lang.Boolean getDmalStatus() {
		return get("dmal_status");
	}

}
