package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCmsStaff<M extends BaseCmsStaff<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStafUserId(java.lang.Integer stafUserId) {
		set("staf_user_id", stafUserId);
	}

	public java.lang.Integer getStafUserId() {
		return get("staf_user_id");
	}

	public void setStafNamePiny(java.lang.String stafNamePiny) {
		set("staf_name_piny", stafNamePiny);
	}

	public java.lang.String getStafNamePiny() {
		return get("staf_name_piny");
	}

	public void setStafTitle(java.lang.String stafTitle) {
		set("staf_title", stafTitle);
	}

	public java.lang.String getStafTitle() {
		return get("staf_title");
	}

	public void setStafPostion(java.lang.String stafPostion) {
		set("staf_postion", stafPostion);
	}

	public java.lang.String getStafPostion() {
		return get("staf_postion");
	}

	public void setStafOffice(java.lang.String stafOffice) {
		set("staf_office", stafOffice);
	}

	public java.lang.String getStafOffice() {
		return get("staf_office");
	}

	public void setStafTel(java.lang.String stafTel) {
		set("staf_tel", stafTel);
	}

	public java.lang.String getStafTel() {
		return get("staf_tel");
	}

	public void setStafEmail(java.lang.String stafEmail) {
		set("staf_email", stafEmail);
	}

	public java.lang.String getStafEmail() {
		return get("staf_email");
	}

	public void setStafCourse(java.lang.String stafCourse) {
		set("staf_course", stafCourse);
	}

	public java.lang.String getStafCourse() {
		return get("staf_course");
	}

	public void setStafResearch(java.lang.String stafResearch) {
		set("staf_research", stafResearch);
	}

	public java.lang.String getStafResearch() {
		return get("staf_research");
	}

	public void setStafSocial(java.lang.String stafSocial) {
		set("staf_social", stafSocial);
	}

	public java.lang.String getStafSocial() {
		return get("staf_social");
	}

	public void setStafResume(java.lang.String stafResume) {
		set("staf_resume", stafResume);
	}

	public java.lang.String getStafResume() {
		return get("staf_resume");
	}

	public void setStafPaper(java.lang.String stafPaper) {
		set("staf_paper", stafPaper);
	}

	public java.lang.String getStafPaper() {
		return get("staf_paper");
	}

	public void setStafProject(java.lang.String stafProject) {
		set("staf_project", stafProject);
	}

	public java.lang.String getStafProject() {
		return get("staf_project");
	}

	public void setStafAward(java.lang.String stafAward) {
		set("staf_award", stafAward);
	}

	public java.lang.String getStafAward() {
		return get("staf_award");
	}

	public void setStafNews(java.lang.String stafNews) {
		set("staf_news", stafNews);
	}

	public java.lang.String getStafNews() {
		return get("staf_news");
	}

	public void setStafTime(java.util.Date stafTime) {
		set("staf_time", stafTime);
	}

	public java.util.Date getStafTime() {
		return get("staf_time");
	}
	
	public void setStafPic(java.lang.String stafPic) {
		set("staf_pic", stafPic);
	}

	public java.lang.String getStafPic() {
		return get("staf_pic");
	}
	
	public void setStafAdvisor(java.lang.String stafAdvisor) {
		set("staf_advisor", stafAdvisor);
	}

	public java.lang.String getStafAdvisor() {
		return get("staf_advisor");
	}
	

}
