package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmFormulaOpt<M extends BaseEmFormulaOpt<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmfoId(java.lang.Integer emfoId) {
		set("emfo_id", emfoId);
	}

	public java.lang.Integer getEmfoId() {
		return get("emfo_id");
	}

	public void setEmfoUserId(java.lang.Integer emfoUserId) {
		set("emfo_user_id", emfoUserId);
	}

	public java.lang.Integer getEmfoUserId() {
		return get("emfo_user_id");
	}

	public void setEmfoType(java.lang.Integer emfoType) {
		set("emfo_type", emfoType);
	}

	public java.lang.Integer getEmfoType() {
		return get("emfo_type");
	}

	public void setEmfoSugg(java.lang.String emfoSugg) {
		set("emfo_sugg", emfoSugg);
	}

	public java.lang.String getEmfoSugg() {
		return get("emfo_sugg");
	}

	public void setEmfoCreateTime(java.util.Date emfoCreateTime) {
		set("emfo_create_time", emfoCreateTime);
	}

	public java.util.Date getEmfoCreateTime() {
		return get("emfo_create_time");
	}

	public void setEmfoIp(java.lang.String emfoIp) {
		set("emfo_ip", emfoIp);
	}

	public java.lang.String getEmfoIp() {
		return get("emfo_ip");
	}

	public void setEmfoStatus(java.lang.Boolean emfoStatus) {
		set("emfo_status", emfoStatus);
	}

	public java.lang.Boolean getEmfoStatus() {
		return get("emfo_status");
	}

}
