package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmFile<M extends BaseEmFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmfoEmfoId(java.lang.Integer emfoEmfoId) {
		set("emfo_emfo_id", emfoEmfoId);
	}

	public java.lang.Integer getEmfoEmfoId() {
		return get("emfo_emfo_id");
	}

	public void setEmfiName(java.lang.String emfiName) {
		set("emfi_name", emfiName);
	}

	public java.lang.String getEmfiName() {
		return get("emfi_name");
	}

	public void setEmfiPath(java.lang.String emfiPath) {
		set("emfi_path", emfiPath);
	}

	public java.lang.String getEmfiPath() {
		return get("emfi_path");
	}

	public void setEnfiDesc(java.lang.String enfiDesc) {
		set("enfi_desc", enfiDesc);
	}

	public java.lang.String getEnfiDesc() {
		return get("enfi_desc");
	}

	public void setEnfiOrder(java.lang.Integer enfiOrder) {
		set("enfi_order", enfiOrder);
	}

	public java.lang.Integer getEnfiOrder() {
		return get("enfi_order");
	}

}
