package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCmsFile<M extends BaseCmsFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setFileNaviId(java.lang.Integer fileNaviId) {
		set("file_navi_id", fileNaviId);
	}

	public java.lang.Integer getFileNaviId() {
		return get("file_navi_id");
	}

	public void setFileTitle(java.lang.String fileTitle) {
		set("file_title", fileTitle);
	}

	public java.lang.String getFileTitle() {
		return get("file_title");
	}

	public void setFileTags(java.lang.String fileTags) {
		set("file_tags", fileTags);
	}

	public java.lang.String getFileTags() {
		return get("file_tags");
	}

	public void setFileContent(java.lang.String fileContent) {
		set("file_content", fileContent);
	}

	public java.lang.String getFileContent() {
		return get("file_content");
	}

	public void setFileUrl(java.lang.String fileUrl) {
		set("file_url", fileUrl);
	}

	public java.lang.String getFileUrl() {
		return get("file_url");
	}

	public void setFileExt(java.lang.String fileExt) {
		set("file_ext", fileExt);
	}

	public java.lang.String getFileExt() {
		return get("file_ext");
	}

	public void setFileTime(java.util.Date fileTime) {
		set("file_time", fileTime);
	}

	public java.util.Date getFileTime() {
		return get("file_time");
	}

	public void setFileUserId(java.lang.Integer fileUserId) {
		set("file_user_id", fileUserId);
	}

	public java.lang.Integer getFileUserId() {
		return get("file_user_id");
	}

	public void setFileHit(java.lang.Integer fileHit) {
		set("file_hit", fileHit);
	}

	public java.lang.Integer getFileHit() {
		return get("file_hit");
	}

	public void setFileIsRestrict(java.lang.Boolean fileIsRestrict) {
		set("file_is_restrict", fileIsRestrict);
	}

	public java.lang.Boolean getFileIsRestrict() {
		return get("file_is_restrict");
	}
	
	public void setFileSize(java.lang.Long fileSize) {
		set("file_size", fileSize);
	}

	public java.lang.Long getFileSize() {
		return get("file_size");
	}

}
