package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmAlgoArgument<M extends BaseDmAlgoArgument<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDmaaDmalId(java.lang.Integer dmaaDmalId) {
		set("dmaa_dmal_id", dmaaDmalId);
	}

	public java.lang.Integer getDmaaDmalId() {
		return get("dmaa_dmal_id");
	}

	public void setDmaaArgu(java.lang.String dmaaArgu) {
		set("dmaa_argu", dmaaArgu);
	}

	public java.lang.String getDmaaArgu() {
		return get("dmaa_argu");
	}

	public void setDmaaNameEn(java.lang.String dmaaNameEn) {
		set("dmaa_name_en", dmaaNameEn);
	}

	public java.lang.String getDmaaNameEn() {
		return get("dmaa_name_en");
	}

	public void setDmaaNameZh(java.lang.String dmaaNameZh) {
		set("dmaa_name_zh", dmaaNameZh);
	}

	public java.lang.String getDmaaNameZh() {
		return get("dmaa_name_zh");
	}

	public void setDmaaDesc(java.lang.String dmaaDesc) {
		set("dmaa_desc", dmaaDesc);
	}

	public java.lang.String getDmaaDesc() {
		return get("dmaa_desc");
	}

	public void setDmaaValue(java.lang.String dmaaValue) {
		set("dmaa_value", dmaaValue);
	}

	public java.lang.String getDmaaValue() {
		return get("dmaa_value");
	}

}
