package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmGeneAttr<M extends BaseEmGeneAttr<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmgeId(java.lang.Integer emgeId) {
		set("emge_id", emgeId);
	}

	public java.lang.Integer getEmgeId() {
		return get("emge_id");
	}

	public void setEmatId(java.lang.Integer ematId) {
		set("emat_id", ematId);
	}

	public java.lang.Integer getEmatId() {
		return get("emat_id");
	}

	public void setEmfaValue(java.lang.String emfaValue) {
		set("emfa_value", emfaValue);
	}

	public java.lang.String getEmfaValue() {
		return get("emfa_value");
	}

}
