package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmGeneCate<M extends BaseEmGeneCate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmgeId(java.lang.Integer emgeId) {
		set("emge_id", emgeId);
	}

	public java.lang.Integer getEmgeId() {
		return get("emge_id");
	}

	public void setEmcaId(java.lang.Integer emcaId) {
		set("emca_id", emcaId);
	}

	public java.lang.Integer getEmcaId() {
		return get("emca_id");
	}

}
