package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmGene<M extends BaseEmGene<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmgeAbbrName(java.lang.String emgeAbbrName) {
		set("emge_abbr_name", emgeAbbrName);
	}

	public java.lang.String getEmgeAbbrName() {
		return get("emge_abbr_name");
	}

	public void setEmgeEnName(java.lang.String emgeEnName) {
		set("emge_en_name", emgeEnName);
	}

	public java.lang.String getEmgeEnName() {
		return get("emge_en_name");
	}

	public void setEmgeZhName(java.lang.String emgeZhName) {
		set("emge_zh_name", emgeZhName);
	}

	public java.lang.String getEmgeZhName() {
		return get("emge_zh_name");
	}

	public void setEmgeCode(java.lang.String emgeCode) {
		set("emge_code", emgeCode);
	}

	public java.lang.String getEmgeCode() {
		return get("emge_code");
	}

	public void setEmgeSrc(java.lang.String emgeSrc) {
		set("emge_src", emgeSrc);
	}

	public java.lang.String getEmgeSrc() {
		return get("emge_src");
	}

	public void setEmgeDesc(java.lang.String emgeDesc) {
		set("emge_desc", emgeDesc);
	}

	public java.lang.String getEmgeDesc() {
		return get("emge_desc");
	}

	public void setEmgeStatus(java.lang.Integer emgeStatus) {
		set("emge_status", emgeStatus);
	}

	public java.lang.Integer getEmgeStatus() {
		return get("emge_status");
	}

	public void setEmgeCreateTime(java.util.Date emgeCreateTime) {
		set("emge_create_time", emgeCreateTime);
	}

	public java.util.Date getEmgeCreateTime() {
		return get("emge_create_time");
	}

	public void setEmgeUpdateTime(java.util.Date emgeUpdateTime) {
		set("emge_update_time", emgeUpdateTime);
	}

	public java.util.Date getEmgeUpdateTime() {
		return get("emge_update_time");
	}

	public void setEmgeSearchCount(java.lang.Integer emgeSearchCount) {
		set("emge_search_count", emgeSearchCount);
	}

	public java.lang.Integer getEmgeSearchCount() {
		return get("emge_search_count");
	}

	public void setEmgeUserId(java.lang.Integer emgeUserId) {
		set("emge_user_id", emgeUserId);
	}

	public java.lang.Integer getEmgeUserId() {
		return get("emge_user_id");
	}

	public void setEmgeSecuId(java.lang.Integer emgeSecuId) {
		set("emge_secu_id", emgeSecuId);
	}

	public java.lang.Integer getEmgeSecuId() {
		return get("emge_secu_id");
	}

}
