package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKnEntrForm<M extends BaseKnEntrForm<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEntrId(java.lang.Integer entrId) {
		set("entr_id", entrId);
	}

	public java.lang.Integer getEntrId() {
		return get("entr_id");
	}

	public void setFormId(java.lang.Integer formId) {
		set("form_id", formId);
	}

	public java.lang.Integer getFormId() {
		return get("form_id");
	}

}
