package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmCate<M extends BaseEmCate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmcaName(java.lang.String emcaName) {
		set("emca_name", emcaName);
	}

	public java.lang.String getEmcaName() {
		return get("emca_name");
	}

	public void setEmcaParentId(java.lang.Integer emcaParentId) {
		set("emca_parent_id", emcaParentId);
	}

	public java.lang.Integer getEmcaParentId() {
		return get("emca_parent_id");
	}

	public void setEmcaImag(java.lang.String emcaImag) {
		set("emca_imag", emcaImag);
	}

	public java.lang.String getEmcaImag() {
		return get("emca_imag");
	}

}
