package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDmAlgoCate<M extends BaseDmAlgoCate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDmacName(java.lang.String dmacName) {
		set("dmac_name", dmacName);
	}

	public java.lang.String getDmacName() {
		return get("dmac_name");
	}

	public void setDmacDesc(java.lang.String dmacDesc) {
		set("dmac_desc", dmacDesc);
	}

	public java.lang.String getDmacDesc() {
		return get("dmac_desc");
	}

}
