package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCmsNews<M extends BaseCmsNews<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNewsNaviId(java.lang.Integer newsNaviId) {
		set("news_navi_id", newsNaviId);
	}

	public java.lang.Integer getNewsNaviId() {
		return get("news_navi_id");
	}

	public void setNewsTitle(java.lang.String newsTitle) {
		set("news_title", newsTitle);
	}

	public java.lang.String getNewsTitle() {
		return get("news_title");
	}

	public void setNewsTags(java.lang.String newsTags) {
		set("news_tags", newsTags);
	}

	public java.lang.String getNewsTags() {
		return get("news_tags");
	}

	public void setNewsContent(java.lang.String newsContent) {
		set("news_content", newsContent);
	}

	public java.lang.String getNewsContent() {
		return get("news_content");
	}

	public void setNewsHit(java.lang.Integer newsHit) {
		set("news_hit", newsHit);
	}

	public java.lang.Integer getNewsHit() {
		return get("news_hit");
	}

	public void setNewsIsTop(java.lang.Boolean newsIsTop) {
		set("news_is_top", newsIsTop);
	}

	public java.lang.Boolean getNewsIsTop() {
		return get("news_is_top");
	}

	public void setNewsTime(java.util.Date newsTime) {
		set("news_time", newsTime);
	}

	public java.util.Date getNewsTime() {
		return get("news_time");
	}

	public void setNewsPic(java.lang.String newsPic) {
		set("news_pic", newsPic);
	}

	public java.lang.String getNewsPic() {
		return get("news_pic");
	}

	public void setNewsUserId(java.lang.Integer newsUserId) {
		set("news_user_id", newsUserId);
	}

	public java.lang.Integer getNewsUserId() {
		return get("news_user_id");
	}

	public void setNewsExprTime(java.util.Date newsExprTime) {
		set("news_expr_time", newsExprTime);
	}

	public java.util.Date getNewsExprTime() {
		return get("news_expr_time");
	}

	public void setNewsIsRestrict(java.lang.Boolean newsIsRestrict) {
		set("news_is_restrict", newsIsRestrict);
	}

	public java.lang.Boolean getNewsIsRestrict() {
		return get("news_is_restrict");
	}
	
	public void setNewsIsPub(java.lang.Boolean newsIsPub) {
		set("news_is_pub", newsIsPub);
	}

	public java.lang.Boolean getNewsIsPub() {
		return get("news_is_pub");
	}

}
