package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKeMenu<M extends BaseKeMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMenuParentId(java.lang.Integer menuParentId) {
		set("menu_parent_id", menuParentId);
	}

	public java.lang.Integer getMenuParentId() {
		return get("menu_parent_id");
	}

	public void setMenuName(java.lang.String menuName) {
		set("menu_name", menuName);
	}

	public java.lang.String getMenuName() {
		return get("menu_name");
	}

	public void setMenuUrl(java.lang.String menuUrl) {
		set("menu_url", menuUrl);
	}

	public java.lang.String getMenuUrl() {
		return get("menu_url");
	}

	public void setMenuIcon(java.lang.String menuIcon) {
		set("menu_icon", menuIcon);
	}

	public java.lang.String getMenuIcon() {
		return get("menu_icon");
	}

	public void setMenuLevel(java.lang.Integer menuLevel) {
		set("menu_level", menuLevel);
	}

	public java.lang.Integer getMenuLevel() {
		return get("menu_level");
	}

	public void setMenuOrder(java.lang.Integer menuOrder) {
		set("menu_order", menuOrder);
	}

	public java.lang.Integer getMenuOrder() {
		return get("menu_order");
	}

	public void setMenuIsLeaf(java.lang.Boolean menuIsLeaf) {
		set("menu_is_leaf", menuIsLeaf);
	}

	public java.lang.Boolean getMenuIsLeaf() {
		return get("menu_is_leaf");
	}

}

