package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmGeneOpt<M extends BaseEmGeneOpt<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmgoId(java.lang.Integer emgoId) {
		set("emgo_id", emgoId);
	}

	public java.lang.Integer getEmgoId() {
		return get("emgo_id");
	}

	public void setEmgoUserId(java.lang.Integer emgoUserId) {
		set("emgo_user_id", emgoUserId);
	}

	public java.lang.Integer getEmgoUserId() {
		return get("emgo_user_id");
	}

	public void setEmgoType(java.lang.Integer emgoType) {
		set("emgo_type", emgoType);
	}

	public java.lang.Integer getEmgoType() {
		return get("emgo_type");
	}

	public void setEmgoSugg(java.lang.String emgoSugg) {
		set("emgo_sugg", emgoSugg);
	}

	public java.lang.String getEmgoSugg() {
		return get("emgo_sugg");
	}

	public void setEmgoCreateTime(java.util.Date emgoCreateTime) {
		set("emgo_create_time", emgoCreateTime);
	}

	public java.util.Date getEmgoCreateTime() {
		return get("emgo_create_time");
	}

	public void setEmgoIp(java.lang.String emgoIp) {
		set("emgo_ip", emgoIp);
	}

	public java.lang.String getEmgoIp() {
		return get("emgo_ip");
	}

	public void setEmgoStatus(java.lang.Boolean emgoStatus) {
		set("emgo_status", emgoStatus);
	}

	public java.lang.Boolean getEmgoStatus() {
		return get("emgo_status");
	}

}
