package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmFormulaAttr<M extends BaseEmFormulaAttr<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmfoId(java.lang.Integer emfoId) {
		set("emfo_id", emfoId);
	}

	public java.lang.Integer getEmfoId() {
		return get("emfo_id");
	}

	public void setEmatId(java.lang.Integer ematId) {
		set("emat_id", ematId);
	}

	public java.lang.Integer getEmatId() {
		return get("emat_id");
	}

	public void setEmfaValue(java.lang.String emfaValue) {
		set("emfa_value", emfaValue);
	}

	public java.lang.String getEmfaValue() {
		return get("emfa_value");
	}

}
