package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmFormula<M extends BaseEmFormula<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmfoAbbrName(java.lang.String emfoAbbrName) {
		set("emfo_abbr_name", emfoAbbrName);
	}

	public java.lang.String getEmfoAbbrName() {
		return get("emfo_abbr_name");
	}

	public void setEmfoEnName(java.lang.String emfoEnName) {
		set("emfo_en_name", emfoEnName);
	}

	public java.lang.String getEmfoEnName() {
		return get("emfo_en_name");
	}

	public void setEmfoZhName(java.lang.String emfoZhName) {
		set("emfo_zh_name", emfoZhName);
	}

	public java.lang.String getEmfoZhName() {
		return get("emfo_zh_name");
	}

	public void setEmfoCode(java.lang.String emfoCode) {
		set("emfo_code", emfoCode);
	}

	public java.lang.String getEmfoCode() {
		return get("emfo_code");
	}

	public void setEmfoSrc(java.lang.String emfoSrc) {
		set("emfo_src", emfoSrc);
	}

	public java.lang.String getEmfoSrc() {
		return get("emfo_src");
	}

	public void setEmfoDesc(java.lang.String emfoDesc) {
		set("emfo_desc", emfoDesc);
	}

	public java.lang.String getEmfoDesc() {
		return get("emfo_desc");
	}

	public void setEmfoStatus(java.lang.Integer emfoStatus) {
		set("emfo_status", emfoStatus);
	}

	public java.lang.Integer getEmfoStatus() {
		return get("emfo_status");
	}

	public void setEmfoCreateTime(java.util.Date emfoCreateTime) {
		set("emfo_create_time", emfoCreateTime);
	}

	public java.util.Date getEmfoCreateTime() {
		return get("emfo_create_time");
	}

	public void setEmfoUpdateTime(java.util.Date emfoUpdateTime) {
		set("emfo_update_time", emfoUpdateTime);
	}

	public java.util.Date getEmfoUpdateTime() {
		return get("emfo_update_time");
	}

	public void setEmfoSearchCount(java.lang.Integer emfoSearchCount) {
		set("emfo_search_count", emfoSearchCount);
	}

	public java.lang.Integer getEmfoSearchCount() {
		return get("emfo_search_count");
	}

	public void setEmfoUserId(java.lang.Integer emfoUserId) {
		set("emfo_user_id", emfoUserId);
	}

	public java.lang.Integer getEmfoUserId() {
		return get("emfo_user_id");
	}

	public void setEmfoSecuId(java.lang.Integer emfoSecuId) {
		set("emfo_secu_id", emfoSecuId);
	}

	public java.lang.Integer getEmfoSecuId() {
		return get("emfo_secu_id");
	}

}
