package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKeOrgan<M extends BaseKeOrgan<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrgaParentId(java.lang.Integer orgaParentId) {
		set("orga_parent_id", orgaParentId);
	}

	public java.lang.Integer getOrgaParentId() {
		return get("orga_parent_id");
	}

	public void setOrgaName(java.lang.String orgaName) {
		set("orga_name", orgaName);
	}

	public java.lang.String getOrgaName() {
		return get("orga_name");
	}

}
