package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKnEntrFile<M extends BaseKnEntrFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEntrId(java.lang.Integer entrId) {
		set("entr_id", entrId);
	}

	public java.lang.Integer getEntrId() {
		return get("entr_id");
	}

	public void setKnfiId(java.lang.Integer knfiId) {
		set("knfi_id", knfiId);
	}

	public java.lang.Integer getKnfiId() {
		return get("knfi_id");
	}

}
