package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKnEntryHistory<M extends BaseKnEntryHistory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setKnehKnenId(java.lang.Integer knehKnenId) {
		set("kneh_knen_id", knehKnenId);
	}

	public java.lang.Integer getKnehKnenId() {
		return get("kneh_knen_id");
	}

	public void setKnehOpraType(java.lang.Integer knehOpraType) {
		set("kneh_opra_type", knehOpraType);
	}

	public java.lang.Integer getKnehOpraType() {
		return get("kneh_opra_type");
	}

	public void setKnehUserId(java.lang.Integer knehUserId) {
		set("kneh_user_id", knehUserId);
	}

	public java.lang.Integer getKnehUserId() {
		return get("kneh_user_id");
	}

	public void setKnehTime(java.util.Date knehTime) {
		set("kneh_time", knehTime);
	}

	public java.util.Date getKnehTime() {
		return get("kneh_time");
	}

	public void setKnehIp(java.lang.String knehIp) {
		set("kneh_ip", knehIp);
	}

	public java.lang.String getKnehIp() {
		return get("kneh_ip");
	}

	public void setKnehText(java.lang.String knehText) {
		set("kneh_text", knehText);
	}

	public java.lang.String getKnehText() {
		return get("kneh_text");
	}

}
