package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKnTree<M extends BaseKnTree<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setKntrParentId(java.lang.Integer kntrParentId) {
		set("kntr_parent_id", kntrParentId);
	}

	public java.lang.Integer getKntrParentId() {
		return get("kntr_parent_id");
	}

	public void setKntrName(java.lang.String kntrName) {
		set("kntr_name", kntrName);
	}

	public java.lang.String getKntrName() {
		return get("kntr_name");
	}

	public void setKntrType(java.lang.Integer kntrType) {
		set("kntr_type", kntrType);
	}

	public java.lang.Integer getKntrType() {
		return get("kntr_type");
	}

}
