package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmMolecular<M extends BaseEmMolecular<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmmoMoluText(java.lang.String emmoMoluText) {
		set("emmo_molu_text", emmoMoluText);
	}

	public java.lang.String getEmmoMoluText() {
		return get("emmo_molu_text");
	}

	public void setEmm0EmfoId(java.lang.Integer emm0EmfoId) {
		set("emm0_emfo_id", emm0EmfoId);
	}

	public java.lang.Integer getEmm0EmfoId() {
		return get("emm0_emfo_id");
	}

	public void setEmmoOrder(java.lang.Integer emmoOrder) {
		set("emmo_order", emmoOrder);
	}

	public java.lang.Integer getEmmoOrder() {
		return get("emmo_order");
	}

}
