package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmAttr<M extends BaseEmAttr<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmatPareId(java.lang.Integer ematPareId) {
		set("emat_pare_id", ematPareId);
	}

	public java.lang.Integer getEmatPareId() {
		return get("emat_pare_id");
	}

	public void setEmatSecuId(java.lang.Integer ematSecuId) {
		set("emat_secu_id", ematSecuId);
	}

	public java.lang.Integer getEmatSecuId() {
		return get("emat_secu_id");
	}

	public void setEmatName(java.lang.String ematName) {
		set("emat_name", ematName);
	}

	public java.lang.String getEmatName() {
		return get("emat_name");
	}

	public void setEmatType(java.lang.Integer ematType) {
		set("emat_type", ematType);
	}

	public java.lang.Integer getEmatType() {
		return get("emat_type");
	}

}
