package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmAttr<M extends BaseEmAttr<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmfoEmcaId(java.lang.Integer emfoEmcaId) {
		set("emfo_emca_id", emfoEmcaId);
	}

	public java.lang.Integer getEmfoEmcaId() {
		return get("emfo_emca_id");
	}

	public void setEmfoSecuId(java.lang.Integer emfoSecuId) {
		set("emfo_secu_id", emfoSecuId);
	}

	public java.lang.Integer getEmfoSecuId() {
		return get("emfo_secu_id");
	}

	public void setEmfoName(java.lang.String emfoName) {
		set("emfo_name", emfoName);
	}

	public java.lang.String getEmfoName() {
		return get("emfo_name");
	}

	public void setEmfoType(java.lang.Integer emfoType) {
		set("emfo_type", emfoType);
	}

	public java.lang.Integer getEmfoType() {
		return get("emfo_type");
	}

}
