package org.kelab.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKnEntry<M extends BaseKnEntry<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setKnenName(java.lang.String knenName) {
		set("knen_name", knenName);
	}

	public java.lang.String getKnenName() {
		return get("knen_name");
	}

	public void setKnenText(java.lang.String knenText) {
		set("knen_text", knenText);
	}

	public java.lang.String getKnenText() {
		return get("knen_text");
	}

	public void setKnenKntrId(java.lang.Integer knenKntrId) {
		set("knen_kntr_id", knenKntrId);
	}

	public java.lang.Integer getKnenKntrId() {
		return get("knen_kntr_id");
	}

	public void setKnenTime(java.util.Date knenTime) {
		set("knen_time", knenTime);
	}

	public java.util.Date getKnenTime() {
		return get("knen_time");
	}

	public void setKnenLastTime(java.util.Date knenLastTime) {
		set("knen_last_time", knenLastTime);
	}

	public java.util.Date getKnenLastTime() {
		return get("knen_last_time");
	}

	public void setKnenStatus(java.lang.Integer knenStatus) {
		set("knen_status", knenStatus);
	}

	public java.lang.Integer getKnenStatus() {
		return get("knen_status");
	}

	public void setKnenTag(java.lang.String knenTag) {
		set("knen_tag", knenTag);
	}

	public java.lang.String getKnenTag() {
		return get("knen_tag");
	}

	public void setKnenCreaUserId(java.lang.Integer knenCreaUserId) {
		set("knen_crea_user_id", knenCreaUserId);
	}

	public java.lang.Integer getKnenCreaUserId() {
		return get("knen_crea_user_id");
	}

	public void setKnenLastUserId(java.lang.Integer knenLastUserId) {
		set("knen_last_user_id", knenLastUserId);
	}

	public java.lang.Integer getKnenLastUserId() {
		return get("knen_last_user_id");
	}

	public void setKnenIsformula(java.lang.Boolean knenIsformula) {
		set("knen_isformula", knenIsformula);
	}

	public java.lang.Boolean getKnenIsformula() {
		return get("knen_isformula");
	}

	public void setKnenIsmolecular(java.lang.Boolean knenIsmolecular) {
		set("knen_ismolecular", knenIsmolecular);
	}

	public java.lang.Boolean getKnenIsmolecular() {
		return get("knen_ismolecular");
	}

	public void setKnenIsdata(java.lang.Boolean knenIsdata) {
		set("knen_isdata", knenIsdata);
	}

	public java.lang.Boolean getKnenIsdata() {
		return get("knen_isdata");
	}

	public void setKnenLastIp(java.lang.String knenLastIp) {
		set("knen_last_ip", knenLastIp);
	}

	public java.lang.String getKnenLastIp() {
		return get("knen_last_ip");
	}

	public void setKnenSecuId(java.lang.Integer knenSecuId) {
		set("knen_secu_id", knenSecuId);
	}

	public java.lang.Integer getKnenSecuId() {
		return get("knen_secu_id");
	}
	public void setKnenTextType(java.lang.String knenTextType) {
		set("knen_text_type", knenTextType);
	}

	public java.lang.String getKnenTextType() {
		return get("knen_text_type");
	}

}
