package org.kelab.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("dm_algo_argument", "id", DmAlgoArgument.class);
		arp.addMapping("dm_algo_cate", "id", DmAlgoCate.class);
		arp.addMapping("dm_algorithm", "id", DmAlgorithm.class);
		arp.addMapping("dm_submit", "id", DmSubmit.class);
		arp.addMapping("em_attr", "id", EmAttr.class);
		arp.addMapping("em_cate", "id", EmCate.class);
		arp.addMapping("em_file", "id", EmFile.class);
		arp.addMapping("em_formula", "id", EmFormula.class);
		arp.addMapping("em_formula_attr", "id", EmFormulaAttr.class);
		arp.addMapping("em_formula_cate", "id", EmFormulaCate.class);
		arp.addMapping("em_formula_opt", "id", EmFormulaOpt.class);
		arp.addMapping("em_molecular", "id", EmMolecular.class);
		arp.addMapping("ke_action", "id", KeAction.class);
		arp.addMapping("ke_auth_code", "id", KeAuthCode.class);
		arp.addMapping("ke_menu", "id", KeMenu.class);
		arp.addMapping("ke_menu_action", "id", KeMenuAction.class);
		arp.addMapping("ke_organ", "id", KeOrgan.class);
		arp.addMapping("ke_role", "id", KeRole.class);
		arp.addMapping("ke_role_menu", "id", KeRoleMenu.class);
		arp.addMapping("ke_security", "id", KeSecurity.class);
		arp.addMapping("ke_session", "id", KeSession.class);
		arp.addMapping("ke_user", "id", KeUser.class);
		arp.addMapping("ke_user_log", "id", KeUserLog.class);
		arp.addMapping("kn_entry_history", "id", KnEntryHistory.class);
		arp.addMapping("kn_tree", "id", KnTree.class);
		arp.addMapping("kn_entr_file", "id", KnEntrFile.class);
		arp.addMapping("kn_entr_form", "id", KnEntrForm.class);
		arp.addMapping("kn_entr_mole", "id", KnEntrMole.class);
		arp.addMapping("kn_entry", "id", KnEntry.class);
		arp.addMapping("kn_file", "id", KnFile.class);
		arp.addMapping("kn_formula", "id", KnFormula.class);
		arp.addMapping("kn_molecular", "id", KnMolecular.class);
		arp.addMapping("kn_tag", "id", KnTag.class);
		arp.addMapping("kn_lang", "id", KnLang.class);
		arp.addMapping("em_attr_type", "id", EmAttrType.class);
	}
}

