package org.kelab.model;

import org.kelab.model.base.BaseCmsAbout;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsAbout extends BaseCmsAbout<CmsAbout> {
	public static final CmsAbout dao = new CmsAbout();
}
