package org.kelab.model;

import org.kelab.model.base.BaseCmsFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsFile extends BaseCmsFile<CmsFile> {
	public static final CmsFile dao = new CmsFile();
}
