package org.kelab.model;

import org.kelab.model.base.BaseCmsLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsLink extends BaseCmsLink<CmsLink> {
	public static final CmsLink dao = new CmsLink();
}
