package org.kelab.model;

import org.kelab.model.base.BaseCmsNaviType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsNaviType extends BaseCmsNaviType<CmsNaviType> {
	public static final CmsNaviType dao = new CmsNaviType();
}
