package org.kelab.model;

import org.kelab.model.base.BaseCmsNavi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsNavi extends BaseCmsNavi<CmsNavi> {
	public static final CmsNavi dao = new CmsNavi();
}
