package org.kelab.model;

import org.kelab.model.base.BaseCmsNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsNews extends BaseCmsNews<CmsNews> {
	public static final CmsNews dao = new CmsNews();
}
