package org.kelab.model;

import org.kelab.model.base.BaseCmsSlide;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsSlide extends BaseCmsSlide<CmsSlide> {
	public static final CmsSlide dao = new CmsSlide();
}
