package org.kelab.model;

import org.kelab.model.base.BaseCmsStaff;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsStaff extends BaseCmsStaff<CmsStaff> {
	public static final CmsStaff dao = new CmsStaff();
}
