package org.kelab.model;

import org.kelab.model.base.BaseDmAlgoCate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmAlgoCate extends BaseDmAlgoCate<DmAlgoCate> {
	public static final DmAlgoCate dao = new DmAlgoCate();
}
