package org.kelab.model;

import org.kelab.model.base.BaseDmAlgorithm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmAlgorithm extends BaseDmAlgorithm<DmAlgorithm> {
	public static final DmAlgorithm dao = new DmAlgorithm();
}
