package org.kelab.model;

import org.kelab.model.base.BaseDmAlgoArgument;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmAlgoArgument extends BaseDmAlgoArgument<DmAlgoArgument> {
	public static final DmAlgoArgument dao = new DmAlgoArgument();
}
