package org.kelab.model;

import org.kelab.model.base.BaseDmSubmit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DmSubmit extends BaseDmSubmit<DmSubmit> {
	public static final DmSubmit dao = new DmSubmit();
}
