package org.kelab.model;

import java.util.List;

import org.kelab.model.base.BaseEmAttrType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmAttrType extends BaseEmAttrType<EmAttrType> {
	public static final EmAttrType dao = new EmAttrType();
	
	public List<EmAttrType> findAll(){
		String sql = "select * from em_attr_type order by id asc";
		return dao.find(sql);
	}
}
