package org.kelab.model;

import org.kelab.model.base.BaseEmAttr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmAttr extends BaseEmAttr<EmAttr> {
	public static final EmAttr dao = new EmAttr();
}
