package org.kelab.model;

import org.kelab.model.base.BaseEmCate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmCate extends BaseEmCate<EmCate> {
	public static final EmCate dao = new EmCate();
}
