package org.kelab.model;

import org.kelab.model.base.BaseEmFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmFile extends BaseEmFile<EmFile> {
	public static final EmFile dao = new EmFile();
}
