package org.kelab.model;

import org.kelab.model.base.BaseEmFormulaOpt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmFormulaOpt extends BaseEmFormulaOpt<EmFormulaOpt> {
	public static final EmFormulaOpt dao = new EmFormulaOpt();
}
