package org.kelab.model;

import org.kelab.model.base.BaseEmFormulaCate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmFormulaCate extends BaseEmFormulaCate<EmFormulaCate> {
	public static final EmFormulaCate dao = new EmFormulaCate();
}
