package org.kelab.model;

import org.kelab.model.base.BaseEmFormula;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmFormula extends BaseEmFormula<EmFormula> {
	public static final EmFormula dao = new EmFormula();
}
