package org.kelab.model;

import org.kelab.model.base.BaseEmFormulaAttr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmFormulaAttr extends BaseEmFormulaAttr<EmFormulaAttr> {
	public static final EmFormulaAttr dao = new EmFormulaAttr();
}
