package org.kelab.model;

import org.kelab.model.base.BaseEmGeneOpt;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmGeneOpt extends BaseEmGeneOpt<EmGeneOpt> {
	public static final EmGeneOpt dao = new EmGeneOpt();
}
