package org.kelab.model;

import org.kelab.model.base.BaseEmGene;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmGene extends BaseEmGene<EmGene> {
	public static final EmGene dao = new EmGene();
}
