package org.kelab.model;

import org.kelab.model.base.BaseEmGeneAttr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmGeneAttr extends BaseEmGeneAttr<EmGeneAttr> {
	public static final EmGeneAttr dao = new EmGeneAttr();
}
