package org.kelab.model;

import org.kelab.model.base.BaseEmGeneCate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmGeneCate extends BaseEmGeneCate<EmGeneCate> {
	public static final EmGeneCate dao = new EmGeneCate();
}
