package org.kelab.model;

import org.kelab.model.base.BaseEmMolecular;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmMolecular extends BaseEmMolecular<EmMolecular> {
	public static final EmMolecular dao = new EmMolecular();
}
