package org.kelab.model;

import org.kelab.model.base.BaseKeAction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KeAction extends BaseKeAction<KeAction> {
	public static final KeAction dao = new KeAction();
}
