package org.kelab.model;

import org.kelab.model.base.BaseKeMenuAction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KeMenuAction extends BaseKeMenuAction<KeMenuAction> {
	public static final KeMenuAction dao = new KeMenuAction();
}
