package org.kelab.model;

import org.kelab.model.base.BaseKeMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KeMenu extends BaseKeMenu<KeMenu> {
	public static final KeMenu dao = new KeMenu();
}
