package org.kelab.model;

import org.kelab.model.base.BaseKeOrgan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KeOrgan extends BaseKeOrgan<KeOrgan> {
	public static final KeOrgan dao = new KeOrgan();
}
