package org.kelab.model;

import org.kelab.model.base.BaseKeRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KeRole extends BaseKeRole<KeRole> {
	public static final KeRole dao = new KeRole();
}
