package org.kelab.model;

import org.kelab.model.base.BaseKeRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KeRoleMenu extends BaseKeRoleMenu<KeRoleMenu> {
	public static final KeRoleMenu dao = new KeRoleMenu();
}
