package org.kelab.model;

import java.util.List;

import org.kelab.model.base.BaseKeSecurity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KeSecurity extends BaseKeSecurity<KeSecurity> {
	public static final KeSecurity dao = new KeSecurity();
	
	public List<KeSecurity> findAll(){
		return dao.find("select * from ke_security");
			}
}
