package org.kelab.model;

import org.kelab.model.base.BaseKeUserLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KeUserLog extends BaseKeUserLog<KeUserLog> {
	public static final KeUserLog dao = new KeUserLog();
}
