package org.kelab.model;

import org.kelab.model.base.BaseKnEntrMole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnEntrMole extends BaseKnEntrMole<KnEntrMole> {
	public static final KnEntrMole dao = new KnEntrMole();
}
