package org.kelab.model;

import org.kelab.model.base.BaseKnEntrForm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnEntrForm extends BaseKnEntrForm<KnEntrForm> {
	public static final KnEntrForm dao = new KnEntrForm();
}
