package org.kelab.model;

import org.kelab.model.base.BaseKnEntrFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnEntrFile extends BaseKnEntrFile<KnEntrFile> {
	public static final KnEntrFile dao = new KnEntrFile();
}
