package org.kelab.model;

import org.kelab.model.base.BaseKnEntry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnEntry extends BaseKnEntry<KnEntry> {
	public static final KnEntry dao = new KnEntry();
}
