package org.kelab.model;

import org.kelab.model.base.BaseKnEntryHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnEntryHistory extends BaseKnEntryHistory<KnEntryHistory> {
	public static final KnEntryHistory dao = new KnEntryHistory();
}
