package org.kelab.model;

import org.kelab.model.base.BaseKnFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnFile extends BaseKnFile<KnFile> {
	public static final KnFile dao = new KnFile();
}
