package org.kelab.model;

import org.kelab.model.base.BaseKnFormula;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnFormula extends BaseKnFormula<KnFormula> {
	public static final KnFormula dao = new KnFormula();
}
