package org.kelab.model;

import org.kelab.model.base.BaseKnGraph;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnGraph extends BaseKnGraph<KnGraph> {
	public static final KnGraph dao = new KnGraph();
}
