package org.kelab.model;

import org.kelab.model.base.BaseKnLang;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnLang extends BaseKnLang<KnLang> {
	public static final KnLang dao = new KnLang();
}
