package org.kelab.model;

import org.kelab.model.base.BaseKnMolecular;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnMolecular extends BaseKnMolecular<KnMolecular> {
	public static final KnMolecular dao = new KnMolecular();
}
