package org.kelab.model;

import org.kelab.model.base.BaseKnTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnTag extends BaseKnTag<KnTag> {
	public static final KnTag dao = new KnTag();
}
