package org.kelab.model;

import org.kelab.model.base.BaseKnTree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class KnTree extends BaseKnTree<KnTree> {
	public static final KnTree dao = new KnTree();
}
